
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CRLPAREN = 25;
  public static final int MULTIPLY = 10;
  public static final int ELSE = 3;
  public static final int PLUS = 8;
  public static final int SQLPAREN = 23;
  public static final int RPAREN = 22;
  public static final int INT = 4;
  public static final int EQUAL = 18;
  public static final int SEMI = 19;
  public static final int NOTEQUAL = 17;
  public static final int WHILE = 7;
  public static final int RETURN = 5;
  public static final int EQUALEQUAL = 16;
  public static final int ERROR = 29;
  public static final int IF = 2;
  public static final int LPAREN = 21;
  public static final int ID = 27;
  public static final int GREATERTHANEQUAL = 15;
  public static final int NUM = 28;
  public static final int COMMA = 20;
  public static final int LESSTHAN = 12;
  public static final int EOF = 0;
  public static final int DIVIDE = 11;
  public static final int MINUS = 9;
  public static final int error = 1;
  public static final int CRRPAREN = 26;
  public static final int LESSTHANEQUAL = 13;
  public static final int SQRPAREN = 24;
  public static final int VOID = 6;
  public static final int GREATERTHAN = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "LESSTHAN",
  "LESSTHANEQUAL",
  "GREATERTHAN",
  "GREATERTHANEQUAL",
  "EQUALEQUAL",
  "NOTEQUAL",
  "EQUAL",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "SQLPAREN",
  "SQRPAREN",
  "CRLPAREN",
  "CRRPAREN",
  "ID",
  "NUM",
  "ERROR"
  };
}

